Repository prgrms-web-devcourse-final-project/WEB3_4_MARCH_BE, pull requests merged in 2025-04, with the labels that each got.

#19 [Refactor] 멤버 도메인내 예외 처리 -> 글로벌 도메인의 공용 클래스에서 예외 처리로 리팩토링 #18
  backend/src/main/java/com/backend/domain/image/service/ImageService.java
  backend/src/main/java/com/backend/domain/image/service/PresignedService.java
  backend/src/main/java/com/backend/domain/member/exception/MemberErrorCode.java
  backend/src/main/java/com/backend/domain/member/exception/MemberException.java
  backend/src/main/java/com/backend/domain/member/service/MemberService.java
  backend/src/main/java/com/backend/global/config/SwaggerConfig.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/exception/GlobalExceptionHandler.java
Labels: enhancement

#21 [Refactor] yml 및 Security 클래스 자잘한 코드 수정 및 추가 #20
  backend/src/main/java/com/backend/global/config/SecurityConfig.java
  backend/src/main/resources/application.yml
Labels: enhancement

#23 [Refactor] 카카오 로그인/회원가입 서비스 로직 리팩토링 #22
  backend/src/main/java/com/backend/domain/member/entity/Member.java
  backend/src/main/java/com/backend/global/auth/kakao/controller/KakaoAuthController.java
  backend/src/main/java/com/backend/global/auth/kakao/dto/LoginResponseDto.java
  backend/src/main/java/com/backend/global/auth/kakao/service/KakaoAuthService.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/resources/application.yml
Labels: enhancement

#26 [Refactor] JWT & 인증 리팩토링 #25
  backend/src/main/java/com/backend/global/auth/exception/JwtException.java
  backend/src/main/java/com/backend/global/auth/kakao/controller/KakaoAuthController.java
  backend/src/main/java/com/backend/global/auth/kakao/service/KakaoAuthService.java
  backend/src/main/java/com/backend/global/auth/kakao/util/JwtUtil.java
  backend/src/main/java/com/backend/global/auth/kakao/util/TokenProvider.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/exception/GlobalExceptionHandler.java
Labels: enhancement

#27 FEAT: feature/BU
  .gitignore
  backend/.gitignore
  backend/src/main/java/com/backend/domain/blockuser/controller/BlockUserController.java
  backend/src/main/java/com/backend/domain/blockuser/dto/request/BlockUserRequest.java
  backend/src/main/java/com/backend/domain/blockuser/dto/response/BlockedUserResponse.java
  backend/src/main/java/com/backend/domain/blockuser/entity/BlockUser.java
  backend/src/main/java/com/backend/domain/blockuser/repository/BlockUserRepository.java
  backend/src/main/java/com/backend/domain/blockuser/service/BlockUserService.java
  backend/src/main/java/com/backend/global/auth/model/CustomUserDetails.java
  backend/src/main/java/com/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/resources/application.yml
Labels: enhancement

#32 FEATURE: 회원추천 기능
  .gitignore
  backend/Dockerfile
  backend/build.gradle
  backend/infra/redis/redis.conf
  backend/src/main/java/com/backend/domain/blockuser/repository/BlockUserRepository.java
  backend/src/main/java/com/backend/domain/member/init/DummyMemberInitializer.java
  backend/src/main/java/com/backend/domain/member/service/MemberService.java
  backend/src/main/java/com/backend/domain/userrecommendation/controller/UserRecommendationController.java
  backend/src/main/java/com/backend/domain/userrecommendation/dto/response/RecommendedUserDto.java
  backend/src/main/java/com/backend/domain/userrecommendation/entity/UserRecommendation.java
  backend/src/main/java/com/backend/domain/userrecommendation/repository/UserRecommendationRepository.java
  backend/src/main/java/com/backend/domain/userrecommendation/scheduler/RecommendationScheduler.java
  backend/src/main/java/com/backend/domain/userrecommendation/service/UserRecommendationService.java
  backend/src/main/java/com/backend/global/base/BaseEntity.java
  backend/src/main/java/com/backend/global/config/RedisConfig.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/redis/service/RedisGeoService.java
  backend/src/main/resources/data.sql
  docker-compose.yml
Labels: enhancement

#35 [Feature] WebSocket, STOMP, Kafka를 이용한 1:1 실시간 채팅 기능 구현
  backend/build.gradle
  backend/deploy-no-build.sh
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/src/main/java/com/backend/domain/chat/controller/ChatController.java
  backend/src/main/java/com/backend/domain/chat/dto/ChatMessage.java
  backend/src/main/java/com/backend/domain/chat/dto/MessageType.java
  backend/src/main/java/com/backend/domain/chat/dto/request/ChatMessageRequest.java
  backend/src/main/java/com/backend/domain/chat/dto/response/ChatMessageResponse.java
  backend/src/main/java/com/backend/domain/chat/dto/response/ChatRoomMessageResponse.java
  backend/src/main/java/com/backend/domain/chat/entity/Chat.java
  backend/src/main/java/com/backend/domain/chat/handler/StompHandler.java
  backend/src/main/java/com/backend/domain/chat/repository/ChatRepository.java
  backend/src/main/java/com/backend/domain/chat/service/chat/ChatService.java
  backend/src/main/java/com/backend/domain/chat/service/chat/ChatServiceImpl.java
  backend/src/main/java/com/backend/domain/chat/service/kafka/KafkaChatConsumer.java
  backend/src/main/java/com/backend/domain/chat/service/kafka/KafkaChatProducer.java
  backend/src/main/java/com/backend/domain/chat/service/redis/RedisPublisher.java
  backend/src/main/java/com/backend/domain/chat/service/redis/RedisSubscriber.java
  backend/src/main/java/com/backend/domain/chat/service/redis/RedisUnreadService.java
  backend/src/main/java/com/backend/domain/chatrequest/dto/request/ChatRequestRequest.java
  backend/src/main/java/com/backend/domain/chatroom/controller/ChatRoomController.java
  backend/src/main/java/com/backend/domain/chatroom/dto/request/ChatRoomRequest.java
  backend/src/main/java/com/backend/domain/chatroom/dto/response/ChatRoomResponse.java
  backend/src/main/java/com/backend/domain/chatroom/entity/ChatRoom.java
  backend/src/main/java/com/backend/domain/chatroom/repository/ChatRoomRepository.java
  backend/src/main/java/com/backend/domain/chatroom/service/ChatRoomService.java
  backend/src/main/java/com/backend/domain/chatroom/service/ChatRoomServiceImpl.java
  backend/src/main/java/com/backend/domain/member/dto/MemberInfoDto.java
  backend/src/main/java/com/backend/domain/member/entity/Member.java
  backend/src/main/java/com/backend/domain/member/service/MemberService.java
  backend/src/main/java/com/backend/global/auth/kakao/util/SecurityUtil.java
  backend/src/main/java/com/backend/global/baseentity/BaseEntity.java
  backend/src/main/java/com/backend/global/config/KafkaTopicConfig.java
  backend/src/main/java/com/backend/global/config/RedisListenerConfig.java
  backend/src/main/java/com/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/backend/global/config/WebSocketConfig.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
  backend/src/main/java/com/backend/global/response/GenericResponse.java
  backend/src/main/resources/static/chat-test.html
  backend/src/main/resources/static/page-list-test.html
  backend/src/main/resources/static/redis-pub-sub-test.html
  backend/src/test/java/com/backend/domain/BackendApplicationTests.java
  docker-compose.yml
Labels: enhancement

#36 FEATURE: 채팅요청기능
  backend/infra/redis/data/appendonlydir/appendonly.aof.1.base.rdb
  backend/infra/redis/data/appendonlydir/appendonly.aof.1.incr.aof
  backend/infra/redis/data/appendonlydir/appendonly.aof.manifest
  backend/infra/redis/data/dump.rdb
  backend/src/main/java/com/backend/domain/chatrequest/controller/ChatRequestController.java
  backend/src/main/java/com/backend/domain/chatrequest/service/ChatRequestService.java
Labels: enhancement

#38 remove: redis data directory git삭제
  backend/infra/redis/data/appendonlydir/appendonly.aof.1.base.rdb
  backend/infra/redis/data/appendonlydir/appendonly.aof.1.incr.aof
  backend/infra/redis/data/appendonlydir/appendonly.aof.manifest
  backend/infra/redis/data/dump.rdb
Labels: documentation

#47 [Fix] 회원가입 이후에도 ROLE_TEMP_USER로 발급받은 토큰으로 남아있어 발생하던 추가정보 입력이 필요합니다 오류 해결
  backend/src/main/java/com/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/backend/domain/member/dto/MemberInfoDto.java
  backend/src/main/java/com/backend/domain/member/dto/MemberModifyRequestDto.java
  backend/src/main/java/com/backend/domain/member/dto/MemberRegisterResponseDto.java
Labels: bug, enhancement

#50 [Feature] Refresh Token에 대한 보안 강화 및 Redis에 저장되는 로직을 개선하여 보안 강화
  backend/src/main/java/com/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/backend/global/auth/jwt/JwtFilter.java
  backend/src/main/java/com/backend/global/auth/kakao/controller/KakaoAuthController.java
  backend/src/main/java/com/backend/global/auth/kakao/service/KakaoAuthService.java
  backend/src/main/java/com/backend/global/auth/kakao/service/RedisRefreshTokenService.java
  backend/src/main/java/com/backend/global/auth/kakao/util/CookieUtil.java
  backend/src/main/java/com/backend/global/auth/kakao/util/KakaoAuthUtil.java
  backend/src/main/java/com/backend/global/auth/kakao/util/TokenProvider.java
  backend/src/main/java/com/backend/global/config/RedisConfig.java
  docker-compose.yml
Labels: enhancement

#51 Feature: 관심키워드 기능 구현
  backend/.gitignore
  backend/src/main/java/com/backend/domain/blockuser/controller/BlockUserController.java
  backend/src/main/java/com/backend/domain/chatrequest/controller/ChatRequestController.java
  backend/src/main/java/com/backend/domain/keyword/controller/KeywordController.java
  backend/src/main/java/com/backend/domain/keyword/dto/response/KeywordCategoryResponse.java
  backend/src/main/java/com/backend/domain/keyword/dto/response/KeywordResponse.java
  backend/src/main/java/com/backend/domain/keyword/entity/Keyword.java
  backend/src/main/java/com/backend/domain/keyword/entity/KeywordCategory.java
  backend/src/main/java/com/backend/domain/keyword/repository/KeywordCategoryRepository.java
  backend/src/main/java/com/backend/domain/keyword/repository/KeywordRepository.java
  backend/src/main/java/com/backend/domain/keyword/service/KeywordService.java
  backend/src/main/java/com/backend/domain/userkeyword/controller/UserKeywordController.java
  backend/src/main/java/com/backend/domain/userkeyword/dto/request/UserKeywordSaveRequest.java
  backend/src/main/java/com/backend/domain/userkeyword/dto/response/UserKeywordResponse.java
  backend/src/main/java/com/backend/domain/userkeyword/entity/UserKeyword.java
  backend/src/main/java/com/backend/domain/userkeyword/repository/UserKeywordRepository.java
  backend/src/main/java/com/backend/domain/userkeyword/service/UserKeywordService.java
  backend/src/main/java/com/backend/domain/userrecommendation/controller/UserRecommendationController.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/sql/data.sql
Labels: enhancement

#52 docs: swagger도메인별로 구분
  backend/src/main/java/com/backend/global/config/SwaggerConfig.java
Labels: documentation

#56 [Fix] 토큰 관련 엔드포인트의 응답 형식 및 로그아웃/재발급 로직 리팩토링
  backend/src/main/java/com/backend/global/auth/kakao/controller/KakaoAuthController.java
  backend/src/main/java/com/backend/global/response/GenericResponse.java
Labels: bug, refactor

#59 [REFACTOR] 채팅 에러를 대비해 로직 보완, 배포용 docker 파일 생성
  .gitignore
  backend/.gitignore
  backend/Dockerfile
  backend/build.gradle
  backend/deploy-no-build.sh
  backend/docker-compose.yml
  backend/src/main/java/com/backend/domain/chat/controller/ChatController.java
  backend/src/main/java/com/backend/domain/chat/dto/ChatMessage.java
  backend/src/main/java/com/backend/domain/chat/entity/Chat.java
  backend/src/main/java/com/backend/domain/chat/repository/ChatRepository.java
  backend/src/main/java/com/backend/domain/chat/service/chat/ChatService.java
  backend/src/main/java/com/backend/domain/chat/service/chat/ChatServiceImpl.java
  backend/src/main/java/com/backend/domain/chat/service/redis/RedisUnreadService.java
  backend/src/main/java/com/backend/domain/chatroom/entity/ChatRoom.java
  backend/src/main/java/com/backend/global/config/SwaggerConfig.java
  backend/src/main/resources/application.yml
Labels: refactor

#74 [Feature, Refactor, Fix] 회원가입 흐름을 하나의 트랜잭션으로 통합 처리, 응답되는 DTO 개선, 프로필 정보 수정 메서드 버그 수정
  backend/src/main/java/com/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/backend/domain/member/dto/MemberInfoDto.java
  backend/src/main/java/com/backend/domain/member/dto/MemberModifyRequestDto.java
  backend/src/main/java/com/backend/domain/member/dto/MemberRegisterRequestDto.java
  backend/src/main/java/com/backend/domain/member/dto/MemberResponseDto.java
  backend/src/main/java/com/backend/domain/member/service/MemberService.java
  backend/src/main/java/com/backend/domain/userkeyword/dto/response/UserKeywordResponse.java
  backend/src/main/java/com/backend/domain/userkeyword/repository/UserKeywordRepository.java
  backend/src/main/java/com/backend/domain/userkeyword/service/UserKeywordService.java
  backend/src/main/java/com/backend/global/auth/kakao/service/KakaoAuthService.java
  backend/src/main/java/com/backend/global/exception/GlobalErrorCode.java
Labels: bug, enhancement, refactor

#79 [FEATURE] 채팅방 토큰만 검증에서 쿠키도 검증으로 수정
  .github/workflows/build-test.yml
  backend/build.gradle
  backend/src/main/java/com/backend/domain/chat/handler/StompHandler.java
  backend/src/main/java/com/backend/domain/chat/repository/ChatRepository.java
  backend/src/main/java/com/backend/domain/chat/service/kafka/KafkaChatConsumer.java
  backend/src/main/java/com/backend/domain/chat/service/kafka/KafkaChatProducer.java
  backend/src/main/java/com/backend/domain/chatroom/dto/response/ChatRoomResponse.java
  backend/src/main/java/com/backend/domain/chatroom/service/ChatRoomServiceImpl.java
  backend/src/main/java/com/backend/global/config/KafkaTopicConfig.java
  backend/src/main/java/com/backend/global/exception/GlobalException.java
  backend/src/test/java/com/backend/domain/chat/ChatRoomServiceTest.java
Labels: enhancement
